### ISSUE TITLE
The model works with V0.9 but not with new layers in V0.10. 

### ISSUE THREAD

**Issue by Arbiter-glitch** [Xilinx/finn#1055]
There is a considerable difference between the output and the expected output. Expected output is the output image received while passing the input image through the software model. I use the latest FINN branch. I trained the network outside the Finn docker. Then exported the qonnx format to Finn. Most of the nodes are rtl while some are hls.
I have included the intermediate models and the build_dataflow_steps.py in the zip file as well as the output received through finn and the expected output. The notebook for running in Pynq is also included. I don't know whether I am doing anything wrong. Also, I took out the last mul node because it just divides by 255 to get the output between 0 and 1.  
[check.zip](https://github.com/Xilinx/finn/files/15076446/check.zip)

[Update:]
It works with old layers of v0.9 but not with the latest branch of FINN v0.10 with RTL layers. Since I want more throughput, RTL layers are better. But for some reason output is all white like, with some feature here and there. Hope this can be solved.
Also I have targeted ZCU104 Ultrascale+ Evaluation Board 
## Expected Output
![expected_finn](https://github.com/Xilinx/finn/assets/70324978/a7ced9e0-9296-4063-bc56-5076c38da604)
## Actual Output Received
![numpy_outfinn](https://github.com/Xilinx/finn/assets/70324978/90d8d3c1-f3a6-4ef8-9eed-f6c9e76d8623)
_Originally posted by @Arbiter-glitch in https://github.com/Xilinx/finn/discussions/1052_

**Comment by Arbiter-glitch** [comment]
[Update]:

To find out why the output is different in finn v0.10. I took Finn v0.9 and started to replace each of the old layers with new RTL layers, I checked at each stage. And it was only after replacing the old Thresholding hls layers with RTL layers , the output varied from the expected. So the problem is might be with the thresholding rtl layers.

**Comment by auphelia** [comment]
See: Issue https://github.com/Xilinx/finn/issues/1060 and PR https://github.com/Xilinx/finn/pull/1077
