### ISSUE TITLE
Problem downloading xrt_202220.2.14.354_22.04-amd64-xrt.deb within run-docker.sh

### ISSUE THREAD

**Issue by maires1306** [Xilinx/finn#1095]
After running `./run-docker.sh quicktest` the process gets stuck on step [10/45] trying to download some files.

![image](https://github.com/Xilinx/finn/assets/13955456/ce5f0418-1e1e-4a4a-bfc7-5a5a63cf5f93)

Apparently it tries to run `wget https://www.xilinx.com/bin/public/openDownload?filename=xrt_202220.2.14.354_22.04-amd64-xrt.deb`, but it keeps waiting for a response after a HTTP request. I tried to download via browser and it worked fine, but I still don't know where to put the file.

**Comment by Ba1tu3han** [comment]
I have encountered this issue for last 3 days. Therefore, I'm using the main brach of v0.10.

**Comment by judrew** [comment]
If the download works using your browser, you could use wget with the user-agent set.
e.g. `wget --user-agent="Mozilla/5.0" [...]`

**Comment by fpjentzsch** [comment]
This was probably fixed in https://github.com/Xilinx/finn/pull/1092

**Comment by maires1306** [comment]
> If the download works using your browser, you could use wget with the user-agent set. e.g. `wget --user-agent="Mozilla/5.0" [...]`

It worked, thanks!

**Comment by auphelia** [comment]
Hi all, 
Thanks for (re)-opening the issue. We are working on a solution, if you don't need XRT for your specific use case, try to skip the build by using `dev` and setting `FINN_SKIP_XRT_DOWNLOAD=1`.

**Comment by auphelia** [comment]
The xrt download link is back up and you should be able to use `dev` without an issue now.

**Comment by auphelia** [comment]
This PR allows to skip the download and instead use a local version of the xrt .deb: https://github.com/Xilinx/finn/pull/1098
Closing this issue for now.
