### ISSUE TITLE
Redeclaration of streams in StreamingDataWidthConverter_hls?

### ISSUE THREAD

**Issue by iksnagreb** [Xilinx/finn#1106]
It seems like these two lines lead to redeclaration of the "intermediate" stream: https://github.com/Xilinx/finn/blob/34f73d557593b1b70dfa808c0ce4894b98808727/src/finn/custom_op/fpgadataflow/hls/streamingdatawidthconverter_hls.py#L82-L86 and https://github.com/Xilinx/finn/blob/34f73d557593b1b70dfa808c0ce4894b98808727/src/finn/custom_op/fpgadataflow/hls/streamingdatawidthconverter_hls.py#L96-L100

Up until now I have not noticed any issues with the generated code (though it might be that scaling up the model recently simply switched the data-width convert from RTL to HLS backend due to the divisibility constraints and thus I could not even notice any issues with the HLS backend). However, some of my recent builds now show the following error messages:

```
/tmp/finn_dev_cberganski/code_gen_cppsim_StreamingDataWidthConverter_hls_0_75956iz3/execute_StreamingDataWidthConverter_hls.cpp:32:28: error: redeclaration of ‘hls::stream<ap_uint<6144> > intermediate’
   32 | hls::stream<ap_uint<6144>> intermediate ("intermediate");
/tmp/finn_dev_cberganski/code_gen_cppsim_StreamingDataWidthConverter_hls_0_75956iz3/execute_StreamingDataWidthConverter_hls.cpp:27:28: note: ‘hls::stream<ap_uint<6144> > intermediate’ previously declared here
   27 | hls::stream<ap_uint<6144>> intermediate ("intermediate");
```
And indeed there are two identical stream declarations almost next to each other. I think one of the stream declaration should be deleted from the code generation? Or is it a copy and paste error and there should indeed be two streams but someone forgot to rename the second one?

### Possible fix
If this is just accidental code duplication, just remove one of the declarations.

**Comment by auphelia** [comment]
Thanks @iksnagreb for catching this! I am closing the issue since the PR is merged.
