### ISSUE TITLE
Memory Primitive Issue

### ISSUE THREAD

**Issue by Ba1tu3han** [Xilinx/finn#1126]
## Prerequisites
Please make sure to check off these prerequisites before submitting a bug report.
- [+] Test that the bug appears on the current version of the dev-branch. Make sure to include the commit hash of the commit you checked out.
- [+] Check that the issue hasn't already been reported, by checking the currently open issues.
- [+] If there are steps to reproduce the problem, make sure to write them down below.
- [ ] If relevant, please include the ONNX files, which were created directly before and/or after the bug.

## Quick summary
I run _./run-docker.sh build_dataflow ~/Desktop/dataflow_build_dir_ for W1A1 CNV model and encountered with an error about Memory Primitive in 15/19 of building steps.

Could you help me how to define it or what I should select?

![Screenshot from 2024-07-06 23-14-52](https://github.com/Xilinx/finn/assets/29502318/af205df8-db89-45d0-852c-92209d4f5d50)
![image](https://github.com/Xilinx/finn/assets/29502318/ede9f563-c920-4494-8e1c-9e918b5b2b73)
[folding_config.json](https://github.com/user-attachments/files/16117429/folding_config.json)

### Steps to Reproduce
Add what needs to be done to reproduce the bug. Add code examples where useful
and make sure to include the resulting ONNX files, and the commit hash you are working on.

1. Clone the FINN repository
2. Checkout the dev branch, with commit hash: [9f0fad5717ae652eaa324583e957161890964555]
3. Start the docker container with the command: [./run-docker.sh build_dataflow ~/Desktop/dataflow_build_dir]

### Possible fix
Setting an option about FIFO.

**Comment by auphelia** [comment]
Hi @Ba1tu3han , from your log files it looks like your build completes successfully.
The info message you are seeing is not an error. But if you like to select a specific memory type for the FIFOs (it defaults to `"auto"`), you can set the `ram_style` argument of the FIFOs in you folding config json. You can use the `final_hw_config.json` as starting point.
