### ISSUE TITLE
404 Not Found [IP: 185...]

### ISSUE THREAD

**Issue by Ba1tu3han** [Xilinx/finn#1136]
Hello,

When run the main or the dev branches with docker it can not find the related IP adress in [12/45]

![image](https://github.com/user-attachments/assets/cd82b60a-dc9d-4b9b-a218-62d3b3d6bfe7)

**Comment by sunnyxiaohu** [comment]
+1

**Comment by auphelia** [comment]
We had a recent change of dependencies, you might want to try adding a `--no-cache` flag at the end of the docker build command in [run-docker.sh](https://github.com/Xilinx/finn/blob/dev/run-docker.sh#L198) and rerun to make sure your container is not building from cache. Like it is done in this (reversed) commit: https://github.com/Xilinx/finn/commit/20e2bbd4bbde6ef78524e05d5fb463a31cba7852

**Comment by sunnyxiaohu** [comment]
@auphelia Thanks for your comment. I have tried the solution and still encountered the same problem.

**Comment by Ba1tu3han** [comment]
Thank you @auphelia It is working after the building without the cache.
