### ISSUE TITLE
ModuleNotFoundError: No module named 'finn.transformation.qonnx'

### ISSUE THREAD

**Issue by arishsatheesan** [Xilinx/finn#1141]
Hello,

I am trying to run the '1-train-mlp-with-brevitas' notebook, and I encountered the error "ModuleNotFoundError: No module named 'finn.transformation.qonnx'".

**Comment by Ba1tu3han** [comment]
Hello @arishsatheesan,

Which FINN version do you use 0.9 or 0.10 ?
