### ISSUE TITLE
New transformation: maxpool past multithreshols

### ISSUE THREAD

**Issue by Tobi-Alonso** [Xilinx/finn#123]
Maxpool can be moved past a multithreshold. As the bit width after a Multithreshold would be smaller, maxpool comparisons would require less hardware and potentially reduce the critical path of maxpool. 

Also, often, before a maxpool, there is a conv. by moving the maxpool past the multithreshold, conv and MT can be implemented with the mvau

**Comment by maltanar** [comment]
This is provided by MoveMaxPoolPastMultiThreshold in https://github.com/Xilinx/finn/blob/dev/src/finn/transformation/streamline/reorder.py
