### ISSUE TITLE
New Transformation: linear op past Global Average pool

### ISSUE THREAD

**Issue by Tobi-Alonso** [Xilinx/finn#124]
Add and mul nodes could be moved past Global average pool which would allow optimizations in resnet50.

There is no transformation for this currently.

Global average pool would be transformed into Accumulation pool plus a Mul node. 
So there are two options:
- first move linear ops past Global average pool. Then Global average pool to Accumulation pool + Mul
- Global average pool to Accumulation pool + Mul. Then move linear ops past Accumulation pool

**Comment by maltanar** [comment]
The average pool implementation strategy ended up being a bit different, but the reorder capability here is provided by `MoveScalarLinearPastInvariants` in
https://github.com/Xilinx/finn/blob/dev/src/finn/transformation/streamline/reorder.py
