### ISSUE TITLE
installation instruction ambiguity 

### ISSUE THREAD

**Issue by bobwmcgrath** [Xilinx/FINN#14]
It's not clear to me where it says "Install HWGQ Caffe in the same directory as FINN: https://github.com/zhaoweicai/hwgq" if that means my directories should be organized as user/FINN and user/hwgq or as user/FINN/hwgq...  Please advise.  In the mean time I will attempt to figure this out with trial and error.  I am using an LXD container if that matters.

**Comment by HPC-Ken** [comment]
Hi,

Your first assumption is correct. Directories should be organised as user/FINN, user/hwgq
