### ISSUE TITLE
c++ Segment Fault when compiling non-folded StreamingFCLayer_Batch

### ISSUE THREAD

**Issue by Tobi-Alonso** [Xilinx/finn#151]
For StreamingFCLayer_Batch with large initializators, g++ may have a Segment fault.
```
g++: internal compiler error: Segmentation fault (program cc1plus)
...
````
clang++ stalls.

This problem disappears when applying folding. 
It would be useful to have Warnings from finn when array sizes pass certain limits

**Comment by auphelia** [comment]
I am closing this issue because it doesn't apply to the current release. Please use version v0.9.
