### ISSUE TITLE
Vs BNN-PYNQ

### ISSUE THREAD

**Issue by eerobert** [Xilinx/FINN#2]
I wonder what is the different between BNN-PYNQ and this git?

What is the current status of this?

And any successful example can be run on board?

Thanks

**Comment by HPC-Ken** [comment]
Hi,

The networks contained in the two projects you mention are the same. The difference is, this repository is the tool that generates hardware designs from caffe prototxt and scales them them to perform well on the target devices.  A user could supply their own prototxt of a network with binary weights and activations and produce a working hardware implementation of that network without doing any hardware design.

The networks included in the README of this project have been tested to work on the PYNQ Z1 board.

Thanks
