### ISSUE TITLE
Create the drivers for the bitstream implementation

### ISSUE THREAD

**Issue by FrancoCapraro** [Xilinx/finn#20]
Hi. I have the final bitstream that i will use to program the FPGA adapted to Ultra96. I so that you have a driver folder in ** FINN/backend/fpga/driver ** 
I want to know how can i use it , to use FINN in my Ultra96. 
Let me know if you dont understand my question.
Thanks.

FC

**Comment by maltanar** [comment]
I'm closing all issues relating to the v.01 version in preparation for the new release. Please note that v0.1 is now deprecated and unsupported.
