### ISSUE TITLE
Allow implementing StreamingFIFO as Xilinx IP FIFOs, relax depth constraint

### ISSUE THREAD

**Issue by maltanar** [Xilinx/finn#203]
Currently, our `StreamingFIFO`s are always implemented as RTL implementations that map to SRLs, which are good in many cases but have some limitations:

1) Depth is limited to 256
2) Always maps to SRLs/LUTMEMs, which is not always desirable e.g. may want to use URAMs on UltraScale+ devices.

To overcome these limitations, it would be good to have a `mem_style` attribute on `StreamingFIFO` that allows different implementations. Xilinx IPI already provides a FIFO generator with customizable depth and resource types. When different `mem_style` types are selected, we would override the default IP VLNV and emit a different series of commands for the IP stitcher that uses the Xilinx FIFO generator instead.

**Comment by quetric** [comment]
Hi @maltanar - this issue seems outdated, the current codebase in `dev` supports implementing StreamingFIFOs by instantiating Vivado FIFO IPs with selectable Block/Distributed/Ultra RAM implementation
