### ISSUE TITLE
Why is it named "FINN"?

### ISSUE THREAD

**Issue by yurueater** [Xilinx/finn#210]
Hi ,My God!
Thank you!
Why Did you name "FINN"?
Thx :)

**Comment by HenniOVP** [comment]
The question was answered on the FINN gitter channel. Unfortunately it is not possible to directly link the answer directly, but the channel is here: https://gitter.im/xilinx-finn/community

The answer given by @maltanar was: "It's the name as it is :-) it was originally going to be an acronym like FIBNN for "fast inference for binary neural nets" but we decided FINN as a name rolled better off the tongue"

**Comment by yurueater** [comment]
I felt good now that it resolved!
Thanks for your kind answer :)
