### ISSUE TITLE
Using the guide from Xilinx

### ISSUE THREAD

**Issue by FrancoCapraro** [Xilinx/finn#23]
Hi, im using this guide/tutorial from Xilinx: 

[https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/18841949/Zynq+UltraScale+MPSoC+Accelerated+Image+Classification+via+Binary+Neural+Network+TechTip](url)

This Tutorial use a CNVW1A1 for Road Signs. I'm trying to change the weights and thres with another training, for example the params of BNN-PYNQ, but i saw some problems to  use it.

 The params in this proyect ( _/aic/src_hw/bnn-pynq-mpsoc/params/road-signs_ )have a different format that Params used in the Git of BNN-PYNQ( [https://github.com/Xilinx/BNN-PYNQ/tree/master/bnn/params/road-signs/cnvW1A1](url) ) so, **How can i make a training for this Tutorial or reuse the Params in BNN-PYNQ ?**

**Comment by maltanar** [comment]
I'm closing all issues relating to the v.01 version in preparation for the new release. Please note that v0.1 is now deprecated and unsupported.
