### ISSUE TITLE
problem launching Jupyter notebook 

### ISSUE THREAD

**Issue by srizwantariq** [Xilinx/finn#260]
Hello guys

Thanks alot for creating this framework. 
I started working on FINN. I followed the getting Started guide. 

I first ran this command  
`./run_docker.sh`

This is the how it executes 
![finn_1PNG](https://user-images.githubusercontent.com/24353102/101909090-4e183880-3bbd-11eb-88fe-6a2d7a356cea.PNG)

Full Terminal Text is here.
[FINN_terminal.txt](https://github.com/Xilinx/finn/files/5679376/FINN_terminal.txt)

then i ran
`./run-docker.sh notebook` 
![finn_2](https://user-images.githubusercontent.com/24353102/101909332-9f282c80-3bbd-11eb-97a6-34d3230fa2bc.PNG)

it didn't workout as explained in the getting started guide. 
`This will launch the Jupyter notebook server inside a Docker container, and print a link on the terminal that you can open in your browser to run the FINN notebooks or create new ones. .. note:: The link will look something like this (the token you get will be different)`

Could you please help me, how can i proceed from here onwards. 

Best regards
Rizwan

**Comment by VanRillaerM** [comment]
- Hit "ctrl-D" to get out of your docker container
- run the command "./run-docker.sh notebook"

You can't use "./run-docker.sh notebook" when you're inside of your container 
(you can see that you are in Docker when your name is collored)

**Comment by maltanar** [comment]
Hi Rizwan, the `run-docker.sh notebook` is to be used from outside the container as VanRillaerM pointed out above. Just an extra clarification:

The instructions in https://finn.readthedocs.io/en/latest/getting_started.html#running-finn-in-docker with titles "Getting an interactive shell for development or experimentation" and "Running the Jupyter notebooks" aren't meant to be followed after each other, they are two different modes.

**Comment by srizwantariq** [comment]
Thanks alot @VanRillaerM  and @maltanar  :)
