### ISSUE TITLE
HLS-Code

### ISSUE THREAD

**Issue by jdwo** [Xilinx/FINN#27]
I cannot make sense of this pragma:

```
#define CASSERT_DATAFLOW(x) ;
```

I searched the internet and did not find an answer to what this does exactly. 

Thank you for your help.

Kind regards

**Comment by HPC-Ken** [comment]
Hi, 

It is a no-op, it doesn't do anything. It used to be an assert for debugging, but now it expands to ignore any argument to it.

Ken

**Comment by jdwo** [comment]
Thank you.
