### ISSUE TITLE
YOLO accelerated with FINN

### ISSUE THREAD

**Issue by Lavr18** [Xilinx/FINN#28]
Dear FINN developers,

I am trying to accelerate YOLO network (this one: https://github.com/xiaohu2015/DeepLearning_tutorials/blob/master/ObjectDetections/yolo/yolo_tf.py) on PYNQ FPGA to achieve real-time object classfication. 
I found FINN framework and very excited about it. However, I am not sure how exactly I can implement the accelerator and if it is possible with FINN for the mentioned network.

Could you please suggest the way I can tackle this?

P.S. I don't have much experience in working with NN, so if you could answer it in simple terms, I very appreciate this.

Thanks in advance,
Aliaksei

**Comment by HPC-Ken** [comment]
Hi,

Yolo networks are not supported in this generation of FINN

Ken
