### ISSUE TITLE
Batch not supported while using cppsim simulations

### ISSUE THREAD

**Issue by Rbourgerie** [Xilinx/finn#281]
We are trying to evaluate the accuracy of the model tfc_w_1_a_1 (on the MNIST data set) on the cppsim (not on a pynq board). We are on the master Branch.
We experience this error while trying to batch in tfc_end_to_end_verification cell 7:
````Exception: Shape missmatch for provided input global_in: found (1, 1, 28, 28) expected (10, 1, 28, 28)```
We then guess that using batch simulations with cppsim is not currently allowed by finn.
We also tried to change the first dimension of the ONNX input to 'N' or '10' such as proposed here : github\onnx\onnx\issues\2182

**Comment by auphelia** [comment]
The verification steps in the builder allow now for input data with larger batch sizes: https://github.com/Xilinx/finn/blob/main/src/finn/builder/build_dataflow_steps.py#L138
Please be aware, that the simulation still feeds one input after the other.
