### ISSUE TITLE
execute_onnx() in cnv_end2end_example throws error

### ISSUE THREAD

**Issue by chhait07** [Xilinx/finn#282]
Hi everybody,
on executing the cnv_end2end_example.ipynb I'm getting an error on function `execute_onnx()`. See the following screenshot. 
[![Issue_execute_CNV-example.png](https://files.gitter.im/5d8cdf19d73408ce4fcc24fc/R4mF/thumb/Issue_execute_CNV-example.png)](https://files.gitter.im/5d8cdf19d73408ce4fcc24fc/R4mF/Issue_execute_CNV-example.png)
I got the same error on executing tfc_end2end_example as you can see [here](https://github.com/Xilinx/finn/issues/275)
In both cases the error messages say that an *output.npy* file is missing. 

Can you tell me why I'm getting this error?

**Comment by maltanar** [comment]
I suspect the PYNQ environment variables (or the initial board/part setting) may be incorrect. Are you able to ssh xilinx@$PYNQ_IP into the board, and when you do, can you see the deployment folder created there? You can try to run the inference manually by invoking `sudo driver.py` in that folder.

A common cause for these errors is if you have forgotten to install the bitstring package on your PYNQ: `sudo pip3 install bitstring`

**Comment by chhait07** [comment]
Hi,
yes I can log into my board and can see the created folder there. I tried to run the inference with no success, see the following screenshot:

![Issue_CNV](https://user-images.githubusercontent.com/78212618/108375434-3df68800-7202-11eb-8741-54f15fd40e31.png)

These are lines 30 - 33 of driver.py:
`import argparse`
`import numpy as np`
`import os`
`from finn.core.datatype import DataType`

The packages argparse and numpy are installed on my board, the os package isn't. on `sudo pip3 install os` I'm getting the message:
*ERROR: Could not find a version that satisfies the requirement os
ERROR: No matching distribution found for os*

The bitstring package is installed on my board. I uninstalled it and re-installed it with no change in behavior.

Do I have to install a finn package (or something like that) on the board?

**Comment by maltanar** [comment]
Correcting my instruction in the previous message (also edited now), can you try with:

`sudo python3.6 driver.py` 

(PYNQ has both python2 and python3, and the FINN drivers must be run with python3)

If this is the driver generated by the end-to-end flow you don't need to install any extra packages, the dependencies are included in the `finn/` subfolder there.

**Comment by chhait07** [comment]
Hi,
I tried command `sudo python3.6 driver.py` getting this:
![Issue_CNV_driver_py](https://user-images.githubusercontent.com/78212618/108585433-d565f300-7348-11eb-8db4-a72900a7348f.png)

When I try the same command on the tfc_end2end_example I'm getting the same error followed by:
*ImportError: cannot import name 'allocate'*

**Comment by chhait07** [comment]
Hi,
after updating my board from PYNQ version 2.4 to 2.6.0 I have now a different behavior. After `sudo python3.6 driver.py` I'm simply getting no output, see the following screenshot:
![execute_onnx_updated](https://user-images.githubusercontent.com/78212618/109261553-3f2a4500-7800-11eb-9f17-2632904530f7.png)

On executing the notebook again I now get a similar error than before: 
![Issue_CNV_updated](https://user-images.githubusercontent.com/78212618/109274929-57a45a80-7814-11eb-9db2-26dd2dfd204d.png)

Do you have an idea about how to solve the problem?

**Comment by chhait07** [comment]
Hi everybody, 
after updating setuptools by `sudo python3 -m pip install --upgrade pip setuptools` I can successfully execute the whole notebook including command `execute_onnx()`.
Thanks for your help!

**Comment by julienmas** [comment]
Hi, did you run `sudo python3 -m pip install --upgrade pip setuptools` on your PC or on the board?
