### ISSUE TITLE
Notebook notebooks\basics\1_brevitas_network_import.ipynb not working

### ISSUE THREAD

**Issue by pete-lennart** [Xilinx/finn#299]
The notebook `notebooks\basics\1_brevitas_network_import.ipynb` does not work anymore since it presumably references an old version of the `bnn-pynq` example in the `brevitas_examples` directory of the `brevitas `repository. I get the following error when executing the notebook:
![image](https://user-images.githubusercontent.com/17381462/112311018-8263c080-8ca5-11eb-9d3c-6244325c87f6.png)

**Comment by pete-lennart** [comment]
PR #300

**Comment by maltanar** [comment]
Thanks for reporting this, #300 is now merged.
