### ISSUE TITLE
Brevitas golden model and FINN-ONNX mismatch for QuantConv2d layer

### ISSUE THREAD

**Issue by jalezeta** [Xilinx/finn#310]
I am attaching a minimal reproducible example for Issue #304, where the Brevitas golden model and the exported FINN-ONNX model execution do not match when the `bias=True` within a simple model with a `QuantConv2d` layer. However, if the `bias=false`, the expected output produced by the Brevitas golden model and the exported FINN-ONNX model match. 

The attached file is a jupyter notebook that creates two simple model with a single `QuantConv2d` layer. One of the models has the `bias=True` and the other one has the `bias=False`. The notebook is meant to offer a minimal reproduce testing scenario for this error. 

[goldenModel_FINN_mismatch.zip](https://github.com/Xilinx/finn/files/6358341/goldenModel_FINN_mismatch.zip)

**Comment by maltanar** [comment]
See above -- there was an issue exporting layers with bias enabled from Brevitas which is now fixed. PR #339 is now merged into `dev` that uses the correct commit hash from Brevitas for this.
