### ISSUE TITLE
    current_inp = np.pad(current_inp, [(0, 0), (0, 7)])

### ISSUE THREAD

**Issue by YZW-explorer** [Xilinx/finn#330]
https://github.com/Xilinx/finn/blob/master/notebooks/end2end_example/cybersecurity/2-export-to-finn-and-verify.ipynb
Hello author, why use np.pad here：
    current_inp = np.pad(current_inp, [(0, 0), (0, 7)])

**Comment by maltanar** [comment]
Hi YZW-explorer, it's better to ask questions in the Gitter channel and not report them as GitHub issues. I've answered your question on the Gitter channel here: https://gitter.im/xilinx-finn/community?at=60a22d9eb10fc85b569edbf0
