### ISSUE TITLE
Finn pip install overwrites existing finn-base install

### ISSUE THREAD

**Issue by fpjentzsch** [Xilinx/finn#358]
Related Gitter discussion: https://gitter.im/xilinx-finn/community?at=60dad875effd491d8c8ec7bc

For some (?) users, the finn pip install in "finn_entrypoint.sh" (`pip install --user -e $FINN_ROOT`) re-installs finn-base from the official main branch even though a different finn-base installation (e.g. at a different commit hash or mounted from a local finn-base clone) already exists.

Finn-base is currently listed as dependency in "setup.cfg" to make the readthedocs build work:
`install_requires = finn-base @ git+https://github.com/Xilinx/finn-base#egg=finn-base`

Curiously, this was never a problem for me; the finn-base requirement is satisfied by other versions without issue.

**Comment by auphelia** [comment]
Hi @fpjentzsch, this issue is solved in the new releases. `finn-base` got deprecated and the source code is now in` qonnx` and `finn`.
