### ISSUE TITLE
showInNetron function dosn't use custom netron port set as enviroment variable.

### ISSUE THREAD

**Issue by HenniOVP** [Xilinx/finn#365]
This requires a few changes to the function itself here: https://github.com/Xilinx/finn/blob/bdfbd4b79088accf92e60fc1fe790e697500dfe7/src/finn/util/visualization.py#L39

And a way to get the port number itself, likely similar to this: https://github.com/Xilinx/finn-base/blob/c928353369f9f4c76e6bbd5c2d0f68c20763c44b/src/finn/util/basic.py#L106

**Comment by maltanar** [comment]
Resolved in #366
