### ISSUE TITLE
Difference between the two tests

### ISSUE THREAD

**Issue by s95github** [Xilinx/finn#37]
Hi,

I have a question, can you please explain to me what's the difference exactly between the FPGA Deployment (CIFAR 10 Layer) and the FPGA Deployment (Quick Test Function)? Also the same question for LeNet.

Yours sincerely.

**Comment by maltanar** [comment]
I'm closing all issues relating to the v.01 version in preparation for the new release. Please note that v0.1 is now deprecated and unsupported.
