### ISSUE TITLE
Nice work and would like to explore more

### ISSUE THREAD

**Issue by eerobert** [Xilinx/FINN#4]
Hi,

I have some question on this repo

1. Which vivado version is tested/supported?
2. Training should be done using HWGQ or ordinary Caffe?
3. How to simulate the inference result before going to long synthesis cycle?
4. While working on cnv with vu9p in vivado 2018.2, the compile script failed.
5. Not enough BRAM when running cnv with pynqz1 in vivado 2018.2

Thanks

**Comment by eerobert** [comment]
i think i have the answer for 1. 4. and 5.
it should be 2017.4

**Comment by HPC-Ken** [comment]
1. We tested with 2017.4.
2. HWGQ only. 
3. See https://github.com/Xilinx/FINN/blob/master/FINN/test/test_hwgq_cnv_w1a1.py. It demonstrates testing a CNV network on MNIST.
4. Not tested with 2018.2. How does it fail?
5. The resource utilization of designs will vary between Vivado releases. You can adjust the amount of BRAM that the tool will attempt to use in https://github.com/Xilinx/FINN/blob/master/FINN/core/config.py. Reduce BRAM_PROPORTION to 0.9 or below.
