### ISSUE TITLE
problem about tfc_end2end_example

### ISSUE THREAD

**Issue by xpww** [Xilinx/finn#407]
When I run this notebook, there will be a prompt like this, I don’t know why went wrong
can someone help me?
![3](https://user-images.githubusercontent.com/88141892/138738467-e32a9aea-05c8-4bc3-b64a-8f43c289464b.png)
![4](https://user-images.githubusercontent.com/88141892/138738466-6dae36f3-e4bc-44a0-b5f6-199ad9cf46f0.png)
![1](https://user-images.githubusercontent.com/88141892/138738478-b894a257-938c-406d-8cd3-2eaf82bb16e1.png)

**Comment by auphelia** [comment]
Hi @xpww , these are just warnings that there are modifications done to the network internally. Usually, they don't change the behavior of the network and are in the standard scenario improvements, but sometimes developers don't want these changes, so the FINN compiler makes the user aware by showing warnings.
