### ISSUE TITLE
Error working on the radioml onnx model

### ISSUE THREAD

**Issue by satishkumar538** [Xilinx/finn#419]
While working on the radioml onnx model provided on https://github.com/Xilinx/finn-examples/releases/download/radioml/radioml_w4a4_small_tidy.onnx I am facing following error (See Screenshot). Please suggest
![1](https://user-images.githubusercontent.com/36513144/141241238-3a3fd3dc-d288-46f1-b59d-1459ce60e7c0.PNG)
![2](https://user-images.githubusercontent.com/36513144/141241253-0853e4b3-3801-4187-80b1-2578d3cb7485.PNG)

.

**Comment by fpjentzsch** [comment]
See discussion: https://github.com/Xilinx/finn/discussions/422
