### ISSUE TITLE
Can you share with us the roadmap of this FINN?

### ISSUE THREAD

**Issue by eerobert** [Xilinx/FINN#6]
I am working on a network with bias. 
And it seems like the current compiler do not support convolution with bias.

If possible, can I have some documentation on what layer is currently supported
And corresponding limitation.

**Comment by HPC-Ken** [comment]
Bias is supported but it is absorbed into thresholds. 

Layers are processed here: https://github.com/Xilinx/FINN/blob/master/FINN/frontend/frontend_hwgq.py 

There is no full documentation on what layers are currently supported
