### ISSUE TITLE
Antivirus detects tests/travis_install.sh as trojan

### ISSUE THREAD

**Issue by Giuseppe5** [Xilinx/finn#64]
When cloning the repository, the file travis_install.sh in the tests folder was detected and eliminated by the antivirus as trojan file.

**Comment by volcacius** [comment]
I can confirm this happened to me as well.

**Comment by maltanar** [comment]
Same here, which is really odd. We don't use travis anyway so I just removed it in 9ccb1ddb70a7c12ff7aa56c706364cd1bdfce1b4
