### ISSUE TITLE
Model simulation fails during synthesis

### ISSUE THREAD

**Issue by reshkor** [Xilinx/FINN#7]
Hello,
I tried running https://github.com/Xilinx/FINN/blob/master/FINN/test/test_hwgq_cnv_w1a1.py to simulate my model. During synthesis part I get the following error:
$ python FINN/test/test_hwgq_cnv_w1a1.py 
test_fpgabackend_rawhls (__main__.TestHWGQCNVw1a1) ... [ConvolutionLayer, LinearLayer, PoolingLayer, LinearLayer, LinearLayer, BipolarThresholdingLayer, ConvolutionLayer, LinearLayer, PoolingLayer, LinearLayer, LinearLayer, BipolarThresholdingLayer, ConvolutionLayer, LinearLayer, LinearLayer, LinearLayer, BipolarThresholdingLayer, FullyConnectedLayer, LinearLayer, LinearLayer, LinearLayer, BipolarThresholdingLayer, FullyConnectedLayer, LinearLayer, LinearLayer, LinearLayer, BipolarThresholdingLayer, FullyConnectedLayer, LinearLayer, LinearLayer, LinearLayer]
[ConvolutionLayer, BipolarThresholdingLayer, PoolingLayer, ConvolutionLayer, BipolarThresholdingLayer, PoolingLayer, ConvolutionLayer, BipolarThresholdingLayer, FullyConnectedLayer, BipolarThresholdingLayer, FullyConnectedLayer, BipolarThresholdingLayer, FullyConnectedLayer, LinearLayer]
Synthesising
ERROR

======================================================================
ERROR: test_fpgabackend_rawhls (__main__.TestHWGQCNVw1a1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "FINN/test/test_hwgq_cnv_w1a1.py", line 90, in test_fpgabackend_rawhls
    hlslayers, self.net, self.dev, res_alloc_predetermined, dirpath, "sfcall-")
  File "/home/steven/FINN/FINN/backend/fpga/backend_fpga.py", line 363, in synthesize
    pipeline = convert(pipeline_in, net, dev, res_alloc, pipeline_ibits)
  File "/home/steven/FINN/FINN/backend/fpga/backend_fpga.py", line 340, in convert
    pipeline = prepare(pipeline, pipeline_ibits)
  File "/home/steven/FINN/FINN/backend/fpga/backend_fpga.py", line 163, in prepare
    pipeline = trns.apply_repeated(pipeline, passConvertToFPGALayers)
  File "/home/steven/FINN/FINN/transforms/transformations.py", line 48, in apply_repeated
    (ret, numChanges) = pass_to_apply(ret)
  File "/home/steven/FINN/FINN/backend/fpga/backend_fpga.py", line 76, in passConvertToFPGALayers
    raise Exception("Unsupported layer type in FPGA backend: %s" % L.get_type())
Exception: Unsupported layer type in FPGA backend: BipolarThresholdingLayer

----------------------------------------------------------------------
The same error occurs if I try to simulate cnv-w1a1 model. However both models can synthesize hardware and create .bit files (when FINN is called with --mode=synth).

**Comment by reshkor** [comment]
I managed to fix this issue by replacing layer restructuring in test_hwgq_cnv_w1a1.py with the one commented in lines 163-170 from https://github.com/Xilinx/FINN/blob/master/FINN/bin/finn.
However now it fails to compile the solution. The error message:

/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "FINN/bin/finn", line 192, in <module>
    process_args(args)
  File "FINN/bin/finn", line 94, in process_args
    generate_hardware(net, dev, gen_bitfile=False)
  File "FINN/bin/finn", line 164, in generate_hardware
    hlspipeline = ret.getSimLayer()
  File "/home/steven/FINN/FINN/backend/fpga/backend_util.py", line 48, in getSimLayer
    subprocess.check_call(["sh", self.getSimCompileScriptPath()])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sh', '/tmp/finn-build-R6F4eC/simcompile.sh']' returned non-zero exit status 1

As I understand it is missing description of main() function. I'm not sure what is supposed to be in the main(). Should it be something like in BNN-PYNQ (https://github.com/Xilinx/BNN-PYNQ/blob/master/bnn/src/network/cnv-pynq/sw/main_python.cpp)?

Thank you in advance.

**Comment by HPC-Ken** [comment]
Please provide more details. It looks like it's going wrong at synthesis. Are you sure you have Vivado installed and in your path?
