### ISSUE TITLE
Running the test suite directly "sh run-docker.sh test" gives 156 errors while running the tests directly just 6

### ISSUE THREAD

**Issue by Marty253** [Xilinx/finn#70]
As I was installing FINN and Vivado. https://finn.readthedocs.io/en/latest/getting_started.html
I tried to test if I installed everything correctly using the command:
"sh run-docker.sh test"
Which runs the test suite directly. Now after I tried to run it I get the following end result:
===== 156 failed, 130 passed, 2 skipped, 25 warnings in 1124.28s (0:18:44) =====
===== 156 failed, 130 passed, 2 skipped, 25 warnings in 930.90s (0:15:30) ======
I ran this twice to make sure it gave the same failed for all the same tests. 
The specific failed tests can be seen in the attached txt file.
[FINN.txt](https://github.com/Xilinx/finn/files/4482731/FINN.txt)

For this my system is the following:
My Ubuntu version is the following:
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 18.04.4 LTS
Release: 18.04
Codename: bionic
Linux martijn 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
I installed the master branch:  git clone https://github.com/Xilinx/finn.git (from master branch on github)

The Vivado I have installed is the following:
source /tools/Xilinx/Vivado/2019.1/settings64.sh
vivado
version
Vivado v2019.1.3 (64-bit)
SW Build 2644227 on Wed Sep  4 09:44:18 MDT 2019
IP Build 2633630 on Wed Sep  4 12:30:14 MDT 2019
Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
$VIVADO_PATH/
bash: /tools/Xilinx/Vivado/2019.1/: Is a directory

I do not have PYNQ system attached to my system but from doing the tests a bit different I did get the results as I expected.
 
This happens if I run the tests as followed:
$ cd finn/
$ sh run-docker.sh
bash: /tools/Xilinx/DocNav/.settings64-DocNav.sh: No such file or directory
bash: /tools/Xilinx/SDK/2019.1/.settings64-SDK_Core_Tools.sh: No such file or directory
$ python setup.py test
The final result is the following:
=========================== short test summary info ============================
FAILED tests/brevitas/test_brevitas_fc.py::test_brevitas_fc_onnx_export_and_exec[2-1-TFC]
FAILED tests/brevitas/test_brevitas_fc.py::test_brevitas_fc_onnx_export_and_exec[2-1-SFC]
FAILED tests/brevitas/test_brevitas_fc.py::test_brevitas_fc_onnx_export_and_exec[2-1-LFC]
FAILED tests/fpgadataflow/test_fpgadataflow_fclayer.py::test_fpgadataflow_fclayer_rtlsim[4-4--1-2-DataType.INT2-DataType.INT2-DataType.BIPOLAR]
FAILED tests/fpgadataflow/test_fpgadataflow_fclayer.py::test_fpgadataflow_fclayer_rtlsim[4-4-1--1-DataType.BIPOLAR-DataType.BIPOLAR-DataType.BIPOLAR]
FAILED tests/fpgadataflow/test_fpgadataflow_ip_stitch.py::test_fpgadataflow_ipstitch_remote_execution
===== 6 failed, 277 passed, 5 skipped, 25 warnings in 21062.15s (5:51:02) ======

I personally have not been able to detect yet where this bug is coming from or how to solve it.
But for someone starting I think it is nice to know this different test method to see if everything installed correctly while this bug exists.

**Comment by maltanar** [comment]
Hi Martin, thanks for reporting this. I had a look and was able to trace this to the `run-docker.sh` script where the test suite is launched, and the .bashrc import was missing. This causes several important environment variables to go missing in the test suite, causing the failures when `python setup.py test`is passed directly to Docker, as opposed to going to interactive shell and then running it. 

Thankfully this is easy enough to fix. https://github.com/Xilinx/finn/commit/b273b562828dc0dcd705538c7929c0adddc04788 fixes this problem. This is now pushed to dev, and will be part of the next release.
