### ISSUE TITLE
A problem with PYNQ board first-time setup

### ISSUE THREAD

**Issue by wanglu4042** [Xilinx/finn#808]
## Prerequisites
Hi, I am a rookie to FPGA , also with finn, sorry to bother you, but i did find some problems when I  was following the tutorial.

## Details
1. get into the finn folder, and do `bash ./run-docker.sh`, there is a line about the board which is 
![image](https://user-images.githubusercontent.com/132076700/235171523-dd412741-d9dd-4049-9ce7-3e9fc75b59bf.png)
Is setting the  `PLATFORM_REPO_PATHS` necessary? 
My board is PYNQ-Z2, how can I change `Using default PYNQ board Pynq-Z1` to Pynq-Z2?
2. When I did this, there was an error.
![image](https://user-images.githubusercontent.com/132076700/235172571-4eabaaea-b6e3-4dba-9a70-c5d62e42ea70.png)
the error was 
![image](https://user-images.githubusercontent.com/132076700/235173402-b37e9c55-c733-4cce-a5f6-58bfa18a7f2c.png)
How can I fix it?
I can skip it and do the next step `Test that you can ssh <PYNQ_USERNAME>@<PYNQ_IP> without having to enter the password. Pass the -v flag to the ssh command if it doesn’t work to help you debug.`, is it OK?

It's also my first time to submit an issue, if there is any problem, please tell me.

Looking forward to the answer!
Sincerely

**Comment by Ba1tu3han** [comment]
@wanglu4042 Could you explain your solution please. Thank you! Bests!

**Comment by wanglu4042** [comment]
> @wanglu4042 Could you explain your solution please. Thank you! Bests!

Hi, I didn't fix that issue, because it would not influence your project. I think  you can just ignore it.
