### ISSUE TITLE
No module named 'finn.core' finn 0.0.1

### ISSUE THREAD

**Issue by MODISENEISO** [Xilinx/finn#858]
![image](https://github.com/Xilinx/finn/assets/47188943/b290bad3-3d38-4791-93d3-d48fc634e728)
I am getting this error while going through tutorial /3-build-accelerator-with-finn.ipynb

**Comment by auphelia** [comment]
Hi @MODISENEISO ,

Could you please use the issue template?
The error message looks to me like the Docker container was not set up correctly. Did you follow the steps on the [Getting Started](https://finn.readthedocs.io/en/latest/getting_started.html) page?

**Comment by MODISENEISO** [comment]
> Hi @MODISENEISO ,
> 
> Could you please use the issue template? The error message looks to me like the Docker container was not set up correctly. Did you follow the steps on the [Getting Started](https://finn.readthedocs.io/en/latest/getting_started.html) page?

Yes I have started going this ruote however I have a challenge mounting the Vivado in the docker.The vivado is installed in a conda env. I added the path for installation before launching docker 
![image](https://github.com/Xilinx/finn/assets/47188943/ca9afafe-c982-4b6f-b972-86737d8b6ff7)

**Comment by MODISENEISO** [comment]
> 
Good day I managed to run the image and have container instance. However the jupyter notebook after starting in the terminal, the link does not open in the browser. Any susgestions as to what could be the cause

**Comment by MODISENEISO** [comment]
> > 
> 
> Good day I managed to run the image and have container instance. However the jupyter notebook after starting in the terminal, the link does not open in the browser. Any susgestions as to what could be the cause

**Comment by MODISENEISO** [comment]
@auphelia

**Comment by fpjentzsch** [comment]
Hi, the original issue seems to be resolved, so I'll close this one. If you still encounter issues with the Jupyter server, please check related discussions (e.g. https://github.com/Xilinx/finn/discussions/854) and create a new discussion if needed.
