### ISSUE TITLE
Finn fresh install with quicktest

### ISSUE THREAD

**Issue by smtalds** [Xilinx/finn#870]
Hi , i am trying to install finn on Ubuntu 18.04 and python 3.8.11. When i run quicktest , i got this error : 

![image](https://github.com/Xilinx/finn/assets/59387657/c4e01d0a-1a26-4cfc-b4a4-e99d84c9a411)

I tried main version. Then i tried other version like v0.8.1 or v0.8 i got this error : I can not solve problems.

![image](https://github.com/Xilinx/finn/assets/59387657/05ecb587-6347-44f5-9b04-584ff15be0b7)

Thanks for answering.

**Comment by fpjentzsch** [comment]
Hi, this dependency issue should be solved on the current dev branch. Can you try that one?

**Comment by smtalds** [comment]
Hi again @fpjentzsch , yes its worked. I can open notebook , but i have still 4xfailed . Is it important ? 

![image](https://github.com/Xilinx/finn/assets/59387657/de5d815e-843b-401f-b5bc-7213fa93d1d3)

Thanks for answering , maybe u can pull this branch for fresh installing. If this is not important , we can close issue. Thanks for everything.

**Comment by fpjentzsch** [comment]
No, these tests are currently marked as "expected fail", so there is no problem.

**Comment by smtalds** [comment]
Hi again @fpjentzsch , I worked on dev branch now , (this is my second pc). I can run same ipynb file my second pc (i installed finn on feb or before then so i dont know which branch), but i can not run same ipynb my first pc (dev branch.) This is error :

![image](https://github.com/Xilinx/finn/assets/59387657/14ce33ff-057d-4d9d-99c8-03afc2a9e62c)
 Can u help me again , thank you sir.

**Comment by smtalds** [comment]
Actually i dont know why x is a list. Then , i tried and export_qonnx is going to same function and i got same error.

**Comment by smtalds** [comment]
I found the answer on https://github.com/Xilinx/finn/issues/853#issuecomment-1640105304. You have to use ishape with torch.rand(ishape).

**Comment by Ba1tu3han** [comment]
> Hi, this dependency issue should be solved on the current dev branch. Can you try that one?

Hello could you explain to me how to use the dev brach? I directly pull the repo that is written in the getting started page. Thanks

**Comment by smtalds** [comment]
> > Hi, this dependency issue should be solved on the current dev branch. Can you try that one?
> 
> Hello could you explain to me how to use the dev brach? I directly pull the repo that is written in the getting started page. Thanks

You can use this command 
`git clone -b <branchname> <remote-repo-url>`  , branchname should be "dev"

**Comment by Ba1tu3han** [comment]
> > > Hi, this dependency issue should be solved on the current dev branch. Can you try that one?
> > 
> > 
> > Hello could you explain to me how to use the dev brach? I directly pull the repo that is written in the getting started page. Thanks
> 
> You can use this command `git clone -b <branchname> <remote-repo-url>` , branchname should be "dev"

It works for me, too. Thank you!
