### ISSUE TITLE
Permission denied when running run-docker quicktest script

### ISSUE THREAD

**Issue by prawin-kumar** [Xilinx/finn#873]
I am trying to run the notebook examples and following the steps mentioned on the Getting Started page of the document. I am encountering an error that has already been discussed in #854 and #673. I would like to point out that I have set up the env path as suggested by @fpjentzsch. 
![ENV_VAR](https://github.com/Xilinx/finn/assets/68505529/15ad88fc-731e-413d-8e3a-ce8e3c7edf8d)
Also verified that docker is running in rootless mode. And have also used a non-home directory as discussed in previous issues.
![Docker_Status](https://github.com/Xilinx/finn/assets/68505529/db728082-1b5b-45a0-9b33-0fce80da0bc3)
However, I keep running into the PermissionError: [Errno 13] Permission denied: './.eggs'. I have attached the console output for the docker script as reference. I have also tried "pip install -U setuptools setuptools_scm wheel" as suggested which didn't help, cleared the docker cache, deps folder in the git repo and fetched the latest changes in the dev branch
[Build.log.txt](https://github.com/Xilinx/finn/files/12303481/Build.log.txt)

**Comment by auphelia** [comment]
The linked discussion is marked as answered, I am closing this issue. @prawin-kumar please feel free to reopen if you are still facing this issue.
