### ISSUE TITLE
ConCat layer Issue 

### ISSUE THREAD

**Issue by pkdeep** [Xilinx/finn#954]
Hi @auphelia  @williamliao28,
I am facing this issue where Concat layer is not getting converted to HLS layer. I tried the transformation InferConCatLayer(), but still it dint infer streaming Concat layer. Can you help with this. I am attacing original and converted .onnx files
![simple_test_hls3 onnx](https://user-images.githubusercontent.com/78947824/296805659-911f902d-4588-4be4-bd4e-9b1b96d80037.png)

![simple_test_hls3 onnx (2)](https://github.com/Xilinx/finn/assets/78947824/ca776437-9119-4771-ac8e-9f82ec0f2cee)
![new_parallel_512x8_w2a2 onnx](https://github.com/Xilinx/finn/assets/78947824/022fc5a5-dde2-47fd-9d3e-1603574bd856)
Here is the original post 
https://github.com/Xilinx/finn/issues/853#issuecomment-1640254839

**Comment by iksnagreb** [comment]
There are scalar multiplications of floating-point type preceding the inputs to the Concat operator, turning the inputs into floating-point as well. Currently, the StreamingConcat does not support floating-point inputs, see here: https://github.com/Xilinx/finn/blob/dev/src/finn/transformation/fpgadataflow/convert_to_hls_layers.py#L1659

Unfortunately, this seems not to be easy to streamline, as the scale factors on each input branch are different. Streamlining the Mul nodes past the Concat layer only works out if they are all equal... It could work using some group-wise scale-factors afterwards, but I am not sure whether there is support for this.

Allowing the StreamingConcat operation to handle floating-point inputs is also not really desirable, as it would leave floating-points in the middle of your model graph (with finn you ideally want to have a continuous chain of integer-only operations). While it should be technically possible, this would require some refactoring of the corresponding HLS code generation.

**Comment by pkdeep** [comment]
Hi @iksnagreb . Thanks for the reply. I could get the Mul factors to be equal. Can this be processed to have a streaming replacement?
 
 I am attaching both the pre-dataflow creation (after HLS) model image and after dataflow creation image. Any insight would be of great help to convert this into a fully streamlined model.


![hls_layers_nw onnx](https://github.com/Xilinx/finn/assets/78947824/09485a3d-6143-475c-a80e-25209df94678)
![dataflow_parent_nw onnx](https://github.com/Xilinx/finn/assets/78947824/eb4e2c20-344e-4ffd-90b8-d1c773943fe7)

**Comment by iksnagreb** [comment]
Hm, conceptually, you now would need something like the `MoveIdenticalOpPastJoinOp` transformation (this is in `finn.transformation.streamline.reorder`), but it seems to be made for two-input join-nodes, while you have an "arbitrary" many inputs join-node. I am not sure whether there already is a suitable streamlining transformation somewhere in finn, but adapting the existing `MoveIdenticalOpPastJoinOp` or introducing a new, similar one seems not too complicated.

**Comment by auphelia** [comment]
Closing this issue, thanks @iksnagreb for the suggestions. @pkdeep, if you have tried out to extend `MoveIdenticalOpPastJoinOp` and would like to contribute to the finn compiler, we're always welcoming contributions from the community 🙂
Please refer to the [contribution guidelines](https://github.com/Xilinx/finn/blob/main/CONTRIBUTING.md) in that case.

**Comment by pkdeep** [comment]
Hi,
Sorry for the delayed response. I was able to move the uniform Multiplication past the Concat layer, although not by "MoveIdenticalOpPastJoinOp" but through some other technique. I removed the mul node, and inserted a new mul node after Concat and the put the exact same value of Param as the deleted Mul node. This helped me in able to convert the model in end-to-en streaming model (except the last Mul and Add node). Thanks
To get uniform Mul node, I inserted "Quantidentity" in each of 4 branches. It gave me same multiplication factor in all 4 branches, but I am not clear why it happened? Can you help in understanding the reason?
